name: circular_bottom_navigation
description: Circular Bottom Navigation (or maybe a tab bar)
version: 0.1.0
author: Iman Khoshabi <iman.neofight@gmail.com>
homepage: https://github.com/imaNNeoFighT/circular_bottom_navigation

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter